namespace SqlCore.Engine.TransactionLog
{
    public static class LogRecord
    {
        public static string GetLogRecordOperationDesc(byte operation) =>
            operation switch
            {
                0x01 => "LOP_FORMAT_PAGE",
                0x02 => "LOP_INSERT_ROWS",
                0x03 => "LOP_DELETE_ROWS",
                0x04 => "LOP_MODIFY_ROW",
                0x05 => "LOP_MODIFY_HEADER",
                0x06 => "LOP_MODIFY_COLUMNS",
                0x07 => "LOP_SET_BITS",
                0x0a => "LOP_SET_FREE_SPACE",
                0x0b => "LOP_DELETE_SPLIT",
                0x0c => "LOP_UNDO_DELETE_SPLIT",
                0x0d => "LOP_EXPUNGE_ROWS",
                0x10 => "LOP_FILE_HDR_MODIFY",
                0x11 => "LOP_CLEAR_GAM_BITS",
                0x12 => "LOP_COUNT_DELTA",
                0x13 => "LOP_ROOT_CHANGE",
                0x15 => "LOP_ENCRYPT_PAGE",
                0x16 => "LOP_INSYSXACT",
                0x7b => "LOP_REVERT_ROW",
                0x7c => "LOP_RECONFIGURE",
                0x7d => "LOP_STRIP_VERSION_INFO",
                0x7e => "LOP_RESET_VERSION_INFO",
                0x80 => "LOP_BEGIN_XACT",
                0x81 => "LOP_COMMIT_XACT",
                0x82 => "LOP_ABORT_XACT",
                0x83 => "LOP_PREP_XACT",
                0x84 => "LOP_MARK_SAVEPOINT",
                0x85 => "LOP_FORGET_XACT",
                0x86 => "LOP_CREATE_FILE",
                0x87 => "LOP_DROP_FILE",
                0x88 => "Unknown",
                0x89 => "LOP_HOBT_DDL",
                0x8a => "LOP_IDENT_NEWVAL",
                0x8b => "LOP_IDENT_SENTVAL",
                0x8c => "LOP_HOBT_DELTA",
                0x8d => "LOP_LOCK_XACT",
                0x8e => "LOP_CREATE_STREAMFILE",
                0x8f => "LOP_MIGRATE_LOCKS",
                0x90 => "LOP_DROP_STREAMFILE",
                0x93 => "LOP_FS_CONTAINER_SIZE_DELTA",
                0x94 => "LOP_BP_DBVER",
                0x95 => "LOP_COPY_VERSION_INFO",
                0x96 => "LOP_BEGIN_CKPT",
                0x99 => "LOP_END_CKPT",
                0x9a => "LOP_BUF_WRITE",
                0xa0 => "LOP_BEGIN_RECOVERY",
                0xa1 => "LOP_END_RECOVERY",
                0xa2 => "LOP_TENANT_LOG",
                0xad => "LOP_CREATE_INDEX",
                0xae => "LOP_DROP_INDEX",
                0xb0 => "LOP_CREATE_ALLOCCHAIN",
                0xb4 => "LOP_CREATE_FTCAT",
                0xb5 => "LOP_DROP_FTCAT",
                0xc8 => "LOP_REPL_COMMAND",
                0xc9 => "LOP_BEGIN_UPDATE",
                0xca => "LOP_END_UPDATE",
                0xcb => "LOP_TEXT_POINTER",
                0xcc => "LOP_TEXT_INFO_BEGIN",
                0xcd => "LOP_TEXT_INFO_END",
                0xce => "LOP_REPL_NOOP",
                0xcf => "LOP_TEXT_VALUE",
                0xd3 => "LOP_SHRINK_NOOP",
                0xd4 => "LOP_FILESTREAM_INFO_BEGIN",
                0xd5 => "LOP_FILESTREAM_INFO_END",
                0xd6 => "LOP_BULK_EXT_ALLOCATION",
                0xd7 => "LOP_SECURITY_OP",
                0xd8 => "LOP_PAGE_REENCRYPT",
                0xd9 => "LOP_CREATE_PHYSICAL_FILE",
                0xdc => "LOP_RANGE_INSERT",
                0xdf => "LOP_CSI_ROWGROUP",
                0xe0 => "LOP_CSI_DELETE_BUFFER",
                0xe1 => "LOP_CSI_DBMP_INVALIDATION",
                0xe9 => "LOP_HK_DEPLOYED",
                0xea => "LOP_HK_UNDEPLOYED",
                0xf2 => "LOP_SLOG_CKPT",
                0xf3 => "LOP_PREPARE_REMOTE_FILE",
                0xf4 => "LOP_CTR_NEST_ABORT",
                0xf5 => "LOP_EE"
            };

        public static string GetLogRecordContextDesc(byte context) =>
            context switch
            {
                0x00 => "LCX_NULL",
                0x01 => "LCX_HEAP",
                0x02 => "LCX_CLUSTERED",
                0x03 => "LCX_INDEX_LEAF",
                0x04 => "LCX_INDEX_INTERIOR",
                0x05 => "LCX_TEXT_MIX",
                0x06 => "LCX_TEXT_TREE",
                0x07 => "LCX_DIAGNOSTICS",
                0x08 => "LCX_GAM",
                0x09 => "LCX_SGAM",
                0x0a => "LCX_IAM",
                0x0b => "LCX_PFS",
                0x0c => "LCX_IDENTITY_VALUE",
                0x0d => "LCX_OBJECT_ID",
                0x0e => "LCX_NONSYS_SPLIT",
                0x11 => "LCX_FILE_HEADER",
                0x12 => "LCX_SCHEMA_VERSION",
                0x13 => "LCX_MARK_AS_GHOST",
                0x14 => "LCX_BOOT_PAGE",
                0x15 => "LCX_SYSCONFIG_PAGE",
                0x16 => "LCX_CTR_ABORTED",
                0x17 => "LCX_BOOT_PAGE_CKPT",
                0x18 => "LCX_DIFF_MAP",
                0x19 => "LCX_ML_MAP",
                0x1a => "LCX_REMOVE_VERSION_INFO",
                0x1b => "LCX_DBCC_FORMATTED",
                0x1c => "LCX_UNLINKED_REORG_PAGE",
                0x1d => "LCX_BULK_OPERATION_PAGE",
                0x1e => "LCX_TRACKED_XDES",
                0x1f => "LCX_ENCRYPT_UNALLOC_PAGE",
                0x20 => "LCX_SORT_PAGE",
                0x21 => "LCX_WORK_FILE_PAGE",
                0x22 => "LCX_RESTORE_BAD_UNALLOC_PAGE",
                0x23 => "LCX_OFF_ROW_PVS",
                0x24 => "LCX_CTR_XACT_CLEANUP",
                0x25 => "LCX_TRY_TRANSITION_TO_NON_CTR",
                0x26 => "LCX_CTR_NEST_ABORTED",
                0x27 => "LCX_CTR_LOG_HOLDUP",
                0x28 => "LCX_LEDGER_TRANSACTIONS"
            };
    }
}
